<a href="https://colab.research.google.com/github/Jenishbh/CS483/blob/master/Final_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.preprocessing import Normalizer
X= [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]
transformer = Normalizer().fit(X)
print(transformer)
transformer.transform(X)

Normalizer(copy=True, norm='l2')


array([[0.18257419, 0.36514837, 0.54772256, 0.73029674],
       [0.37904902, 0.45485883, 0.53066863, 0.60647843],
       [0.42616235, 0.47351372, 0.5208651 , 0.56821647],
       [0.44694921, 0.48132991, 0.51571062, 0.55009133]])

In [10]:
from sklearn.preprocessing import Binarizer
X=[[1.1,2.2,3.3],
   [4.4,5.5,6.6],
   [7.7,8.8,9.9]]
transformer = Binarizer(5.5).fit(X)
print(transformer)
transformer.transform(X)

Binarizer(copy=True, threshold=5.5)


array([[0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 1.]])

In [48]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

 


a = tf.constant(4,5,6)
b = tf.constant(4,5,6)
type(a)
print(a - b)


2.3.0
tf.Tensor([0 0 0 0 0 0], shape=(6,), dtype=int16)


In [44]:
a = tf.constant([1, 2, 3], shape=[1, 3])
print(a)
b = tf.constant([4,5,6], shape=[3, 1])
print(b)
c = tf.matmul(a, b)
print(c)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[4]
 [5]
 [6]], shape=(3, 1), dtype=int32)
tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [63]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.transpose(x)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [62]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[7, 5], [5, 7], [7, 7],[3, 3], [4, 6], [1, 4], [0, 0],[2,2],[8, 7],[6,8],[5,5],[3,7]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print(kmeans.labels_)
print(kmeans.predict([[0, 0], [12, 3]]))
kmeans.cluster_centers_

[1 1 1 0 1 0 0 0 1 1 1 1]
[0 1]


array([[1.5  , 2.25 ],
       [5.625, 6.5  ]])

In [72]:

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

# Use only one feature
diabetes_X = diabetes_X[:, np.newaxis, 2]

# Split the data into training/testing sets
diabetes_X_train = diabetes_X[[6], [8], [10], [14], [18]]
diabetes_X_test = diabetes_X[[8], [9], [11], [16], [12]]

# Split the targets into training/testing sets
diabetes_y_train = diabetes_y[[7], [9], [13], [17.5], [18]]
diabetes_y_test = diabetes_y[[11], [8.5], [15], [18], [11]]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(diabetes_y_test, diabetes_y_pred))

# Plot outputs
plt.scatter(diabetes_X_test, diabetes_y_test,  color='black')
plt.plot(diabetes_X_test, diabetes_y_pred, color='blue', linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

IndexError: ignored